title: Shyama Sastha Krishnamoorthy Srinivasan
logo: /assets/images/portrait (2).jpeg
description: Graduate researcher at IIIT-Delhi. Aiming to employ HCI + Critical Computing to design and develop an HCAI Framework for proactive health and wellbeing.
baseurl: "" 
url: "https://shyamsastha.github.io" 
production_url: "https://shyamsastha.github.io"

repository: shyamsastha/shyamsastha.github.io

github_username: shyamsastha
permalink: /blog/:year/:month/:title.html

twitter:
  username: SasthaShyama

# Use the Minimal theme
remote_theme: pages-themes/minimal

# Enable necessary plugins
plugins:
  - jekyll-remote-theme # Required for using remote themes
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions

# Customize Minimal theme (optional)
minimal:
  skin: dark  # This setting does not exist by default; dark mode needs CSS customization

# Set default layout
defaults:
  - scope:
      path: ""
    values:
      layout: default
